[package]
name = "solana-vrf-example"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.8.14"
switchboard-v2 = "0.1.1"
bytemuck = "1.7.2"
